### PR TITLE
Fix download icon in material theme, fixes #83

### LINKED ISSUE #83: Bad download icon with material theme
With latest [master and latest material 5.1](https://github.com/majkinetor/mm-docs/blob/master/requirements.txt) icon is not shown correctly any more as download arrow but as ``:

See build here: https://majkinetor.github.io/mm-docs-template:

image

### PR DESCRIPTION
**Pull request by timvink**
Fixes download icon for material theme, #83 

Demo:

image

### CODE REVIEW

**Comment by timvink** [comment]
Hee, thanks for letting me know!

I would like to reproduce this issue locally, but both `mkdocs build` and `mkdocs serve` work fine for me. Perhaps you have a minimal reproducable example? Or even better, an alternative solution?

Tim

**Comment by rmueck** [comment]
> Hee, thanks for letting me know!
> 
> I would like to reproduce this issue locally, but both `mkdocs build` and `mkdocs serve` work fine for me. Perhaps you have a minimal reproducable example? Or even better, an alternative solution?
> 
> Tim

Hey Tim,
as mentioned `mkdocs build` works like a charm. When i start `mkdocs serve` it initially looks fine, but the error occurs, when i try to navigate  in the `dev` server site. 

Cheers

**Comment by rsansores** [comment]
Can confirm @rmueck.

Same exception "Tried to write more data than Content-Lenght"

**Comment by timvink** [comment]
Thanks @rsansores . 

I don't have time to work on this currently, hope to revisit in a couple of weeks or so. Feel free to pick up the PR :)

**Comment by Kanaduchi** [comment]
Hello! Any update on this PR? Does it work with latest version of mkdocs-material? (5.3.0)

**Comment by timvink** [comment]
Thanks @Kanaduchi for the pointer! Quite sure that will fix the `HTTPOutputError`. 

I also fixed the icon size, which was wrong. If someone can confirm that it works for them as well, we can flag this as ready for merge to zhaoterryy.

**Comment by Kanaduchi** [comment]
> Thanks @Kanaduchi for the pointer! Quite sure that will fix the `HTTPOutputError`.
> 
> I also fixed the icon size, which was wrong. If someone can confirm that it works for them as well, we can flag this as ready for merge to zhaoterryy.

I verified it locally.

One issue that I see is:
image

I think you also need to remove `a.string = '\uE2C4'`

**Comment by timvink** [comment]
? I think you also need to remove `a.string = '\uE2C4'`

That line was already removed. I now also removed any unnecessary attributes from the svg. 

Renders correctly on chrome and safari, and latest `mkdocs-material` version:

image

**Comment by Kanaduchi** [comment]
No it looks great! Thank you! Hope this PR will be merged soon

**Comment by timvink** [comment]
@zhaoterryy ready for merge 😃

**Comment by timvink** [comment]
I found & fixed another bug, present on `master` and also in this `fix-download-icon` branch

`soup = BeautifulSoup(html, 'html.parser')` actually does more than just parse the HTML, it also applies some 'fixes'. This leads to unintended side effects (other than inserting the button). For example, when used in combination with [mknotebooks](https://github.com/greenape/mknotebooks) BeautifulSoup will break the HTML and the jupyter notebooks don't render correctly (on some browsers / platforms). Took a while to find that bug, but solution was easy: insert the button using basic python string manipulation.

**Comment by zhaoterryy** [comment]
@timvink cheers!

**Pull request merged**
